<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class AddressesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('addresses')->insert([
            // thoroughfares
            // v é igual ao -
            //   é igual a espaço
            // . é igual a ponto .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
['city_id'=>'1','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GERALDO BARBOSA, 296', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'1','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GERALDO BARBOSA, 296', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'3','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'PREF. ROLANDO MOREIRA, 118', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'3','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'RUI LINO, 264', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'3','clinic'=>'CLÍNICA SANTA CLARA', 'thoroughfare'=>'AV', 'address'=>'RUI LINO, 264', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'3','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'PREF. ROLANDO MOREIRA, 118', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'3','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'RUI LINO, 264', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'3','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GABRIEL ACÁCIO MEZERA, 32', 'complement'=>null, 'district'=>'FERREIRA SILVA'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 798', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'POLICLÍNICA CRUZEIRO DO SUL', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 828', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'POLICLÍNICA CRUZEIRO DO SUL', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 828', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 447', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CLÍNICA DE DOENÇAS RENAIS DO VALE DO JURUÁ', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 610', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'ODONTOMED', 'thoroughfare'=>'AV', 'address'=>'LAURO MULLER, 300', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'POLICLÍNICA CRUZEIRO DO SUL', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 828', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 447', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CENTRO MÉDICO JURUÁ', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CENTRO MÉDICO LABSUL', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 798', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'CEL. MÂNCIO LIMA, 644', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 1610', 'complement'=>null, 'district'=>'25 DE AGOSTO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 798', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 798', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CLÍNICA DE DOENÇAS RENAIS DO VALE DO JURUÁ', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 610', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'MÂNCIO LIMA, 450', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'PHYSICAL STUDIO', 'thoroughfare'=>'AV', 'address'=>'COPACABANA, 599 - 1° ANDAR', 'complement'=>null, 'district'=>' COPACABANA'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 1610', 'complement'=>null, 'district'=>'25 DE AGOSTO'],
['city_id'=>'6','clinic'=>'NEURO-FISIO', 'thoroughfare'=>'RUA', 'address'=>'PEDRO TELES, 481', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'POLICLÍNICA CRUZEIRO DO SUL', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 828', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CENTRO MÉDICO JURUÁ', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CLÍNICA MAIS SAÚDE', 'thoroughfare'=>'AV', 'address'=>'CEL. MÂNCIO LIMA, 644', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CLÍNICA MAIS SAÚDE', 'thoroughfare'=>'AV', 'address'=>'CEL. MÂNCIO LIMA, 644', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'CEL. MÂNCIO LIMA, 637', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 464', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 1610', 'complement'=>null, 'district'=>'25 DE AGOSTO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 453', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'RODRIGUES ALVES, 362', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'POLICLÍNICA CRUZEIRO DO SUL', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 828', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ISABEL DE\'U, 296', 'complement'=>null, 'district'=>'FORMOSO'],
['city_id'=>'6','clinic'=>'CENTRO MÉDICO JURUÁ', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 472', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'TARAUACÁ, 210', 'complement'=>null, 'district'=>'AABB'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 447', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 1610', 'complement'=>null, 'district'=>'25 DE AGOSTO'],
['city_id'=>'6','clinic'=>'PSICOCLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'REGO BARROS, 344', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'POLICLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 828', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'6','clinic'=>'CENTRO MÉDICO JURUÁ', 'thoroughfare'=>'AV', 'address'=>'15 DE NOVEMBRO, 384', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'8','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'MARECHAL DEODORO, 901', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'13','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CEL. FONTENELE DE CASTRO, 270', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'13','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DIAMANTINO AUGUSTO DE MACEDO, 625, SALA B', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'13','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CEL. FONTENELE DE CASTRO, 270', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'13','clinic'=>'CEMEF - CENTRO MÉDICO DA FAMÍLIA', 'thoroughfare'=>'RUA', 'address'=>'CEL. FONTENELE DE CASTRO, 270', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'FELICIDADE, 66', 'complement'=>null, 'district'=>'PETRÓPOLIS'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'DA ALEGRIA, 69', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'LABORATÓRIO DNA', 'thoroughfare'=>'RUA', 'address'=>'CASTRO ALVES, 35', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1729', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CASTRO ALVES, 35', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 338', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOBABY', 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 490', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOBABY', 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 490', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'MASTOCLIN', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 - SALA J', 'complement'=>'Galeria Castro', 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MILTON MATOS, 81', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 486', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 486', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'MASTOCLIN', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 - SALA J', 'complement'=>'Galeria Castro', 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PERFIL PLASTIC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 758', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CLIMPE', 'thoroughfare'=>'RUA', 'address'=>'MANOEL RODRIGUES DE SOUZA, 48', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINIVITA', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 725', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'EDIFÍCIO SANTOS', 'thoroughfare'=>'RUA', 'address'=>'BENJAMIN CONSTANT, 977 - SALA 210 ', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLIMEJ', 'thoroughfare'=>'RUA', 'address'=>'MINAS GERAIS, 1305', 'complement'=>null, 'district'=>'PREVENTÓRIO'],
['city_id'=>'16','clinic'=>'SERIMAGEM', 'thoroughfare'=>'RUA', 'address'=>'FCO. MANGABEIRA, 253 - SALA 03', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA WILLIANA', 'thoroughfare'=>'RUA', 'address'=>'FCº MANGABEIRA, 265 - SALA 101', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CENTRO MÉDICO DO ACRE', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 178', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICAS REUNIDAS', 'thoroughfare'=>'RUA', 'address'=>'JOSÉ DE MELO, 107 - SALA 03', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA CASA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 54', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CENTRO MÉDICO DO ACRE', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 178', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MARANHÃO III, 749', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 490', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 434', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'JOSÉ DE MELO, 107', 'complement'=>null, 'district'=>'SALA 08 - BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICAS REUNIDAS', 'thoroughfare'=>'RUA', 'address'=>'DA ALEGRIA, 46', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MINAS GERAIS, 1305', 'complement'=>null, 'district'=>'PREVENTÓRIO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 182', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1917', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1848', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MILTON MATOS, 770', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'TRAV', 'address'=>'DA ALEGRIA, 69', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DELMAR PISMEL, 125', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1919', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GENERAL VIEIRA DE MELO, 1411', 'complement'=>null, 'district'=>'CONJUNTO ESPERANÇA'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1729', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'AV', 'address'=>'RECANTO VERDE, 154', 'complement'=>null, 'district'=>'PRIMAVERA'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA LÚCIA', 'thoroughfare'=>'RUA', 'address'=>'19 DE NOVEMBRO, 74', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'ANEXO À CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'HENRIQUE DIAS, 25', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 - SALA J', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 361 - SALA H', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GRAÇA ARANHA - QUADRA 36 - CASA 01 - Nº 08', 'complement'=>null, 'district'=>'CONJ. BELA VISTA'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 383', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'TRAV', 'address'=>'ALAGOAS, 32', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 505', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'CAMPO DO RIO BRANCO, 360', 'complement'=>null, 'district'=>'CAPOEIRA'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'EQUADOR, 229', 'complement'=>null, 'district'=>'HABITASA'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'ALAGOAS, 32', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 505', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'DA ALEGRIA, 69', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 - SALA J', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SERIMAGEM', 'thoroughfare'=>'RUA', 'address'=>'FRANCISCO MANGABEIRA, 253', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'FISIOCLIN', 'thoroughfare'=>'RUA', 'address'=>'19 DE NOVEMBRO, 74', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 505', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SUPERMERCADO ARAÚJO', 'thoroughfare'=>'RODOVIA', 'address'=>'AC 40, 484', 'complement'=>null, 'district'=>'06 DE AGOSTO'],
['city_id'=>'16','clinic'=>'ATACADÃO MIX', 'thoroughfare'=>'AV', 'address'=>'CEARÁ, 517', 'complement'=>null, 'district'=>'JARDIM DE ALAH'],
['city_id'=>'16','clinic'=>'SUPERMERCADO ARAÚJO', 'thoroughfare'=>'RUA', 'address'=>'RIO DE JANEIRO, 730', 'complement'=>null, 'district'=>'IVETE VARGAS'],
['city_id'=>'16','clinic'=>'SUPERMERCADO ARAÚJO', 'thoroughfare'=>'RUA', 'address'=>'DO AVIÁRIO, 122', 'complement'=>null, 'district'=>'AVIÁRIO'],
['city_id'=>'16','clinic'=>'SUPERMERCADO ARAÚJO', 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 3718, CONJ. TANGARÁ', 'complement'=>null, 'district'=>'ESTAÇÃO EXPERIMENTAL'],
['city_id'=>'16','clinic'=>'SUPERMERCADO ARAÚJO', 'thoroughfare'=>'RUA', 'address'=>'ISAURA PARENTE, 722', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SUPERMERCADO ARAÚJO', 'thoroughfare'=>'VIA', 'address'=>'CHICO MENDES, 3678', 'complement'=>null, 'district'=>'AREAL'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 490', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'GUAPORÉ, 369 - SALA 06', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689 - 2º ANDAR', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 31 - SALA C', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA LÚCIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1919', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICAS REUNIDAS', 'thoroughfare'=>'RUA', 'address'=>'JOSÉ DE MELO, 107 - SALA 03', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SERIMAGEM', 'thoroughfare'=>'RUA', 'address'=>'FRANCISCO MANGABEIRA, 253 - SALA 10', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINORL - CLÍNICA DE OTORRINOLARINGOLOGIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1729', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINORL - CLÍNICA DE OTORRINOLARINGOLOGIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1729', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MARECHAL DEODORO, 1123', 'complement'=>null, 'district'=>'IPASE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'MATRIZ: AV', 'address'=>'QUINTINO BOCAIÚVA, 1407', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'FILIAL: AV', 'address'=>'MARECHAL DEODORO, 572', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DA ALEGRIA, 46', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CER - CENTRO ESPECIALIZADO EM REABILITAÇÃO', 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 310', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MARANHÃO III, 749', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DA ALEGRIA, 46', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1848', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MILTON MATOS, 770', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'19 DE NOVEMBRO, 74', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'ANEXO À CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'PERDIZ, 79', 'complement'=>null, 'district'=>'CONJ. OURICURI'],
['city_id'=>'16','clinic'=>'ATENDIMENTO DOMICILIAR', 'thoroughfare'=>null, 'address'=>null, 'complement'=>null, 'district'=>null],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 840', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'PÊSSEGO, 96', 'complement'=>null, 'district'=>'MORADA DO SOL'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 383', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA RIO BRANCO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 526', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 246', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'FISIOTERAPIA DERMATOvFUNCIONAL', 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 119', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SENSORIAL CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'EQUADOR, 229', 'complement'=>null, 'district'=>'HABITASA'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICAS REUNIDAS', 'thoroughfare'=>'RUA', 'address'=>'JOSÉ DE MELO, 107 - SALA 03', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SERIMAGEM', 'thoroughfare'=>'RUA', 'address'=>'FRANCISCO MANGABEIRA, 253 - SALA 10', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'FELICIDADE, 66', 'complement'=>null, 'district'=>'PETRÓPOLIS'],
['city_id'=>'16','clinic'=>'CENTRO MÉDICO DO ACRE', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 178', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA RIO BRANCO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 526', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HENRIQUE DIAS, 77', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CENTRO MÉDICO DO ACRE', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 178', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CEMAP', 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 434', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEMAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 967', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1258 - SALA 101', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 361 - SALA H', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CENTRO EMPRESARIAL RIO BRANCO', 'thoroughfare'=>'AV', 'address'=>'BRASIL, 303 - SALA 705', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'GALERIA WILLIANA', 'thoroughfare'=>'RUA', 'address'=>'FCº MANGABEIRA, 265 - SALA 106', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'COPACABANA, 148', 'complement'=>null, 'district'=>'VILLAGE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 31 - SALA A', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 2032', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEMAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 967', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 568', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CEMAP', 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 434', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 568', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CLÍNICAS REUNIDAS', 'thoroughfare'=>'RUA', 'address'=>'JOSÉ DE MELO, 107 - SALA 08', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 152', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'CAMPO DO RIO BRANCO, 252', 'complement'=>null, 'district'=>'CAPOEIRA'],
['city_id'=>'16','clinic'=>'FISIOCLIN', 'thoroughfare'=>'RUA', 'address'=>'19 DE NOVEMBRO, 74', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 234 - SALA 01', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA DE MEDICINA TROPICAL DO ACRE', 'thoroughfare'=>'RUA', 'address'=>'CASTRO ALVES, 380', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 178', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CENTRO MÉDICO DO ACRE', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 178', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 415', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 125', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1861', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 2047', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CASTRO ALVES, 35', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1909', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MINAS GERAIS, 1305', 'complement'=>null, 'district'=>'PREVENTÓRIO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'ESTRADA', 'address'=>'DAS PLACAS, 966', 'complement'=>null, 'district'=>'PLACAS'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 338', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'SILVESTRE COELHO, 434', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 182', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CHECKUP', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1857', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ANTUNES ALENCAR, 159', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 - SALA J', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PRONTOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1940', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PERFIL PLASTIC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 758', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MILTON MATOS, 81', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CLIMPE', 'thoroughfare'=>'RUA', 'address'=>'MANOEL RODRIGUES DE SOUZA, 48', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'19 DE NOVEMBRO, 64', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SÃO CAMILO', 'thoroughfare'=>'RUA', 'address'=>'GENERAL VIEIRA DE MELO, 1411', 'complement'=>null, 'district'=>'CONJUNTO ESPERANÇA'],
['city_id'=>'16','clinic'=>'MEDAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 226', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'ESPAÇO SER', 'thoroughfare'=>'TRAV', 'address'=>'PE. MANOEL DA NÓBREGA, 120', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'FLORA FARMA', 'thoroughfare'=>'RUA', 'address'=>'MARECHAL DEODORO, 1123', 'complement'=>null, 'district'=>'IPASE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DA ALEGRIA, 46', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RIO GRANDE DO SUL, 182', 'complement'=>null, 'district'=>'DOM GIOCONDO'],
['city_id'=>'16','clinic'=>'NUTRI CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'MANOEL CASSIANO, 90', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'MAIS ACADEMIA', 'thoroughfare'=>'RUA', 'address'=>'ISAURA PARENTE, 2820', 'complement'=>null, 'district'=>'ESTAÇÃO EXPERIMENTAL'],
['city_id'=>'16','clinic'=>'SNC - SPORTS NUTRITION CENTER', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1407', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'MAIS ACADEMIA', 'thoroughfare'=>'RUA', 'address'=>'ISAURA PARENTE, 2820', 'complement'=>null, 'district'=>'ESTAÇÃO EXPERIMENTAL'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DAS OLIVEIRAS, 607', 'complement'=>null, 'district'=>'TROPICAL'],
['city_id'=>'16','clinic'=>'ANEXO À REAL CONVÊNIOS', 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 151', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 361 - SALA A', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINI SAÚDE', 'thoroughfare'=>'RUA', 'address'=>'MARECHAL DEODORO, 690', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CLÍNICA CEMAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 967', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA LÚCIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1919', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA RIO BRANCO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 526', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'JOSÉ MAGALHÃES, 63', 'complement'=>null, 'district'=>'VILA IVONETE'],
['city_id'=>'16','clinic'=>'VIDERE - CENTRO DE OFTALMOLOGIA ESPECIALIZADA', 'thoroughfare'=>'RUA', 'address'=>'MILTON MATOS, 315', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'FLORIANO PEIXOTO, 1127', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CLINIVITA', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 725', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 18', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'SANTA CASA DE MISERICÓRDIA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 54', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA RIO BRANCO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 526', 'complement'=>null, 'district'=>' BOSQUE'],
['city_id'=>'16','clinic'=>'CLINIVITA', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 725', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CER - CENTRO ESPECIALIZADO EM REABILITAÇÃO', 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 310', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA RIO BRANCO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 526', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINORL - CLÍNICA DE OTORRINOLARINGOLOGIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1729', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA LÚCIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1919', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINORL - CLÍNICA DE OTORRINOLARINGOLOGIA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1729', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINIVITA', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 725', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 SALA 05', 'complement'=>null, 'district'=>' BOSQUE'],
['city_id'=>'16','clinic'=>'CARDIOCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1227', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINIVITA', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 725', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61 - SALA 05', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'EDIFÍCIO SANTOS', 'thoroughfare'=>'RUA', 'address'=>'BENJAMIN CONSTANT, 416 - SALA 210', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1919', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'JOÃO FCO DA CUNHA, 350', 'complement'=>null, 'district'=>'VILA IVONETE'],
['city_id'=>'16','clinic'=>'CLÍNICA DERMATOCLIN', 'thoroughfare'=>'TRAV', 'address'=>'DA ALEGRIA, 69', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA WILLIANA', 'thoroughfare'=>'RUA', 'address'=>'FCº MANGABEIRA, 265 - SALA 01', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1919', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 226', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA PARK', 'thoroughfare'=>'TRAV', 'address'=>'CAMPO DO RIO BRANCO, 308', 'complement'=>null, 'district'=>'SALA 08 - CAPOEIRA'],
['city_id'=>'16','clinic'=>'CLÍNICA DERMATOCLIN', 'thoroughfare'=>'TRAV', 'address'=>'DA ALEGRIA, 69', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'CAMPO DO RIO BRANCO, 252', 'complement'=>null, 'district'=>'CAPOEIRA'],
['city_id'=>'16','clinic'=>'CENTRO EMPRESARIAL RIO BRANCO', 'thoroughfare'=>'AV', 'address'=>'BRASIL, 303 - SALA 301', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CORONEL ALEXANDRINO, 601 - APTO 05', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'MARIS CLÍNICA DE PSICOLOGIA', 'thoroughfare'=>'RUA', 'address'=>'FRANCISCO ALENCAR, 33', 'complement'=>null, 'district'=>'VILA IVONETE'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PONTO CLIN', 'thoroughfare'=>'RUA', 'address'=>'MARTE, 1075', 'complement'=>null, 'district'=>'MORADA DO SOL'],
['city_id'=>'16','clinic'=>'MARIS CLÍNICA DE PSICOLOGIA', 'thoroughfare'=>'RUA', 'address'=>'FRANCISCO ALENCAR, 33', 'complement'=>null, 'district'=>'VILA IVONETE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DA ALEGRIA, 46', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'COPACABANA, 148 - TÉRREO', 'complement'=>null, 'district'=>'CONJUNTO VILLAGE'],
['city_id'=>'16','clinic'=>'MULTI CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 235', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA DE PSICOLOGIA INTEGRAR', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, SALA 31 D', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CUIDAR', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1917', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290', 'complement'=>null, 'district'=>'TÉRREO - BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'FRANCISCO ALENCAR, 33', 'complement'=>null, 'district'=>'VILA IVONETE'],
['city_id'=>'16','clinic'=>'PONTO CLIN', 'thoroughfare'=>'RUA', 'address'=>'MARTE, 1075 - APTO 03', 'complement'=>null, 'district'=>'MORADA DO SOL'],
['city_id'=>'16','clinic'=>'CER - CENTRO ESPECIALIZADO EM REABILITAÇÃO', 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 310', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAMÃO, 110', 'complement'=>null, 'district'=>'MORADA DO SOL'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290', 'complement'=>null, 'district'=>'TÉRREO - BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALDOMIRO LOPES, 356', 'complement'=>null, 'district'=>'CONQUISTA'],
['city_id'=>'16','clinic'=>'SENSORIAL CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'EQUADOR, 229', 'complement'=>null, 'district'=>'HABITASA'],
['city_id'=>'16','clinic'=>'CLÍNICA EQUILÍBRIO', 'thoroughfare'=>'RUA', 'address'=>'DELMAR PISMEL, 125', 'complement'=>null, 'district'=>'CONJ. GUIOMARD SANTOS'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'INDEPENDÊNCIA, 272', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 568', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VINTE E QUATRO DE JANEIRO, 291', 'complement'=>null, 'district'=>'SEIS DE AGOSTO'],
['city_id'=>'16','clinic'=>'CLÍNICA CUIDAR', 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 1917', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290 - TÉRREO', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626 B', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'NETUNO, 439', 'complement'=>null, 'district'=>'MORADA DO SOL'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'GUAPORÉ, 369 - SALA 06', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'16','clinic'=>'CLÍNICA SANTA INÊS', 'thoroughfare'=>'RUA', 'address'=>'CEL. JOSÉ GALDINO, 626', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 182', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 505', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'ALAGOAS, 32', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 505', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLINIVITA', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 725', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA RIO BRANCO', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 526', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA SÃO CAMILO', 'thoroughfare'=>'RUA', 'address'=>'GENERAL VIEIRA DE MELO, 1411', 'complement'=>null, 'district'=>'CONJUNTO ESPERANÇA'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'TRAV', 'address'=>'ANTUNES DE ALENCAR, 152', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CER - CENTRO ESPECIALIZADO EM REABILITAÇÃO', 'thoroughfare'=>'RUA', 'address'=>'GUIOMARD SANTOS, 310', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'PSICOCLEAN', 'thoroughfare'=>'RUA', 'address'=>'DOM BOSCO, 290', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 125', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 2047', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 505', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'NAÇÕES UNIDAS, 182', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'RECANTO VERDE, 154', 'complement'=>null, 'district'=>'PRIMAVERA'],
['city_id'=>'16','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'VALÉRIO MAGALHÃES, 63', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'HOSPITAL SANTA JULIANA', 'thoroughfare'=>'RUA', 'address'=>'ALVORADA, 806', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'GALERIA CASTRO', 'thoroughfare'=>'RUA', 'address'=>'GOUDWASSER SANTOS, 61', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'16','clinic'=>'CLÍNICA CEDIAC', 'thoroughfare'=>'RUA', 'address'=>'HUGO CARNEIRO, 689', 'complement'=>null, 'district'=>'BOSQUE'],
['city_id'=>'17','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'SENA MADUREIRA, 87', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'19','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'CUNHA VASCONCELOS, 714', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'19','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MONSENHOR TÁVORA, 216', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'19','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AVELINO CHAVES, 855', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'19','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DOM JÚLIO MATIOLLI, 168', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'20','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'CASTELO BRANCO, 1440', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'20','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'CASTELO BRANCO, 1440', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'20','clinic'=>'POSTO DE COLETA', 'thoroughfare'=>'AV', 'address'=>'SEN. EDUARDO ASSMAR, 104', 'complement'=>null, 'district'=>'COHAB'],
['city_id'=>'21','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 274', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'21','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'QUINTINO BOCAIÚVA, 274', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'22','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RODOVALDO NOGUEIRA, 306', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1280', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MONSENHOR COUTINHO, 891', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1199', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'TAPAJÓS, 685', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIM, 7404 - A', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAFAEL ASSAYAG, 94', 'complement'=>null, 'district'=>'ALVORADA I'],
['city_id'=>'178','clinic'=>'SHOPPING MILLENIUM CENTER', 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - LOJAS 243 E 215B', 'complement'=>null, 'district'=>'TORRE MÉDICA - CHAPADA'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'JOAQUIM NABUCO, 1700', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'GETÚLIO VARGAS, 1199', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1280', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - LOJAS 243 E 215B', 'complement'=>null, 'district'=>'TORRE MÉDICA - CHAPADA'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1062', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>'SHOPPING MILLENIUM CENTER', 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - SALA 105', 'complement'=>null, 'district'=>'CHAPADA'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'TARUMA, 1169', 'complement'=>null, 'district'=>'PRAÇA 14 DE JANEIRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'AUTAZ MIRIM, 282 - PISO L1', 'complement'=>null, 'district'=>'SHOPPING CIDADE LESTE'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MONSENHOR COUTINHO, 835', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'JOAQUIM NABUCO, 1359', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1280', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - LOJAS 243 E 215B', 'complement'=>null, 'district'=>'TORRE MÉDICA - CHAPADA'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'JOAQUIM NABUCO, 1700 A', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1280', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1280', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - LOJAS 243 E 215B', 'complement'=>null, 'district'=>'TORRE MÉDICA - CHAPADA'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - LOJAS 243 E 215B', 'complement'=>null, 'district'=>'TORRE MÉDICA - CHAPADA'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'RAMOS FERREIRA, 1280', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'AUTAZ MIRIN, 327', 'complement'=>null, 'district'=>'TANCREDO NEVES'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'MAJOR GABRIEL, 823', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'178','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DJALMA BATISTA, 1661 - LOJAS 243 E 215B', 'complement'=>null, 'district'=>'TORRE MÉDICA - CHAPADA'],
['city_id'=>'804','clinic'=>'EDIFÍCIO BIOCENTER', 'thoroughfare'=>null, 'address'=>'709/909 SUL, TÉRREO, SOBRELOJA, 2º e 4º ANDARES', 'complement'=>null, 'district'=>'PLANO PILOTO'],
['city_id'=>'804','clinic'=>null, 'thoroughfare'=>null, 'address'=>'SMHN Q2, BL A, SALA 207', 'complement'=>null, 'district'=>'EDIFÍCIO DE CLÍNICAS'],
['city_id'=>'804','clinic'=>null, 'thoroughfare'=>null, 'address'=>'SEUPS EQ 712/912 CONJ. B, BL 01 - LOJAS 02 E 03', 'complement'=>null, 'district'=>'ASA SUL'],
['city_id'=>'977','clinic'=>'CMI - CENTRO MÉDICO INTEGRADO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816 - 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAÚDE', 'thoroughfare'=>'RUA', 'address'=>'17A, 1437', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE MÉDICA SUGITA', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 804', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'L, 334', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO ANÁLISE', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 181', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160, 4° ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CEMED - CENTRO MÉDICO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 673', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CEMED - CENTRO MÉDICO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 673', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160 - 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160, 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210, 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE MÉDICA SUGITA', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 804', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CEMED - CENTRO MÉDICO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 673', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO DE DIAGNÓSTICO BIO IMAGEM', 'thoroughfare'=>'RUA', 'address'=>'9A, 145', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160, 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'9A, 145', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'R3, 220', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'B, 765', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'ALAMEDA', 'address'=>'RICARDO PARANHOS, 799 - EDIFÍCIO PROSPÉRE - SALA 04', 'complement'=>null, 'district'=>'SETOR MARISTA'],
['city_id'=>'977','clinic'=>'CEDITE - CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210 - 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'FILIAL: av', 'address'=>'T-10 C/ AVENIDA T-15, 460', 'complement'=>null, 'district'=>'SETOR BUENO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'MATRIZ: av', 'address'=>'DR. ISMERINO S. DE CARVALHO, 789', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CEDITE - CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210 - 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'AV', 'address'=>'B, 765', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210 - 5º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210, 6º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CMI - CENTRO MÉDICO INTEGRADO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816, 1º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210 - 1º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160 - 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO DE DIAGNÓSTICO BIO IMAGEM', 'thoroughfare'=>'RUA', 'address'=>'9A, 145', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CEMED - CENTRO MÉDICO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 673', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO MARIELA PIRES', 'thoroughfare'=>'RUA', 'address'=>'6A, 135, 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210, 7º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160 - 6º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210, 7º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'IHG - INSTITUTO DE HEMOTERAPIA DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'7A, 158', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'L, 200', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'9A, 110', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'29A, 975', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'29A, 178', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'MATRIZ: av', 'address'=>'DR. ISMERINO S. DE CARVALHO, 789', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'FILIAL: av', 'address'=>'Tv10 C/ AV Tv15, 460', 'complement'=>null, 'district'=>'SETOR BUENO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 746', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'9A, 110', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'MATRIZ: av', 'address'=>'DR. ISMERINO S. DE CARVALHO, 789', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'FILIAL: av', 'address'=>'T-10 C/ AVENIDA T-15, 460', 'complement'=>null, 'district'=>'SETOR BUENO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'B, 765', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO DE MEDICINA AMIN DAHER', 'thoroughfare'=>'RUA', 'address'=>'17A, 899, 11º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'R3, 220', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'CLÍNICA DE DOENÇAS RENAIS', 'thoroughfare'=>'RUA', 'address'=>'R3, 180', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'RENALCLÍNICA', 'thoroughfare'=>'AV', 'address'=>'R1, QD R2, LT. 11, N. 99', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'CMI - CENTRO MÉDICO INTEGRADO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816 - 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160, 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210 - 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CMI - CENTRO MÉDICO INTEGRADO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816, 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210, 6º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO VALÉRIA FROTA', 'thoroughfare'=>'RUA', 'address'=>'9A, 160, 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO DE OLHOS DE GOIÂNIA', 'thoroughfare'=>'RUA', 'address'=>'9B, 48', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'UNIDADE CLÍNICA', 'thoroughfare'=>'RUA', 'address'=>'9A, 344', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CLÍNICA SAN RAFAEL', 'thoroughfare'=>'RUA', 'address'=>'29A, 289', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO CLÍNICO AEROPORTO', 'thoroughfare'=>'RUA', 'address'=>'9A, 210, 1º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO GOIANO DE OTORRINO', 'thoroughfare'=>'AV', 'address'=>'L, 220 - ESQ. C / 7A', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CMI - CENTRO MÉDICO INTEGRADO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816, 2º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'CENTRO MÉDICO SAULO LOPES DE MORAES', 'thoroughfare'=>'RUA', 'address'=>'9B C/ AV B, Nº 129', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'B, 765', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'CMI - CENTRO MÉDICO INTEGRADO', 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 816, 3º ANDAR', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'B, 765', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'9A, 145', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'MATRIZ: av', 'address'=>'DR. ISMERINO S. DE CARVALHO, 789', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'FILIAL: av', 'address'=>'T-10 C/ AVENIDA T-15, 460', 'complement'=>null, 'district'=>'SETOR BUENO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'DR. ISMERINO S. DE CARVALHO, 746', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'B, 765', 'complement'=>null, 'district'=>'SETOR OESTE'],
['city_id'=>'977','clinic'=>'INSTITUTO SÍRIO LIBANÊS', 'thoroughfare'=>'RUA', 'address'=>'7A, 35', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO SÍRIO LIBANÊS', 'thoroughfare'=>'RUA', 'address'=>'7A, 35', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO SÍRIO LIBANÊS', 'thoroughfare'=>'RUA', 'address'=>'7A, 35', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO SÍRIO LIBANÊS', 'thoroughfare'=>'RUA', 'address'=>'7A, 35', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'977','clinic'=>'INSTITUTO SÍRIO LIBANÊS', 'thoroughfare'=>'RUA', 'address'=>'7A, 35', 'complement'=>null, 'district'=>'SETOR AEROPORTO'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'PRESIDENTE DUTRA, 3064', 'complement'=>null, 'district'=>'CAIARI'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'PRESIDENTE DUTRA, 3064', 'complement'=>null, 'district'=>'CAIARI'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'PRESIDENTE DUTRA, 3064', 'complement'=>null, 'district'=>'CAIARI'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'JÚLIO DE CASTILHO, 282', 'complement'=>null, 'district'=>'CENTRO'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'AV', 'address'=>'PRESIDENTE DUTRA, 3064', 'complement'=>null, 'district'=>'CAIARI'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'4382','clinic'=>'HOSPITAL 9 DE JULHO', 'thoroughfare'=>'AV', 'address'=>'PRESIDENTE DUTRA, 3064', 'complement'=>null, 'district'=>'CAIARI'],
['city_id'=>'4382','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'ÁLVARO MAIA, 1600', 'complement'=>null, 'district'=>'OLARIA'],
['city_id'=>'5270','clinic'=>null, 'thoroughfare'=>'RUA', 'address'=>'DO ORATÓRIO, 1369', 'complement'=>null, 'district'=>'MOCA'],
 ]);

        $this->command->info('Endereços importados com sucesso!');
    }
}