<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class SpecialtiesSeeder extends Seeder
{
    public function run()
    {
        DB::table('specialties')->insert([

        ['name'=>'acupuntura','description'=>'Ramo da medicina tradicional chinesa e um método de tratamento chamado complementar de acordo com a nova terminologia da OMS','city_id'=>'16'],
['name'=>'acupuntura','description'=>'Ramo da medicina tradicional chinesa e um método de tratamento chamado complementar de acordo com a nova terminologia da OMS','city_id'=>'977'],
['name'=>'alergologia','description'=>'Diagnóstico e tratamento das doenças alérgicas','city_id'=>'16'],
['name'=>'alergologia','description'=>'Diagnóstico e tratamento das doenças alérgicas','city_id'=>'977'],
['name'=>'angiologia','description'=>'É a área da medicina que estuda o tratamento das doenças do aparelho circulatório','city_id'=>'16'],
['name'=>'angiologia','description'=>'É a área da medicina que estuda o tratamento das doenças do aparelho circulatório','city_id'=>'977'],
['name'=>'aparelhos auditivos','description'=>'É um pequeno dispositivo eletrônico que você usa dentro ou atrás da orelha. Ele emite sons mais altos para que uma pessoa com perdaauditiva possa ouvir, comunicar e participar plenamente das atividades diárias','city_id'=>'977'],
['name'=>'audiometria','description'=>'Exame utilizado para avaliação da audição','city_id'=>'16'],
['name'=>'biópsia','description'=>'É a remoção de uma pequena quantidade de tecido para avaliação anatomopatológica da presença (ou não) de câncer','city_id'=>'16'],
['name'=>'biópsia','description'=>'É a remoção de uma pequena quantidade de tecido para avaliação anatomopatológica da presença (ou não) de câncer','city_id'=>'4382'],
['name'=>'cardiologia','description'=>'Trata de doenças relacionadas com o coração e sistema vascular','city_id'=>'6'],
['name'=>'cardiologia','description'=>'Trata de doenças relacionadas com o coração e sistema vascular','city_id'=>'16'],
['name'=>'cardiologia','description'=>'Trata de doenças relacionadas com o coração e sistema vascular','city_id'=>'977'],
['name'=>'cardiologia pediátrica','description'=>'Ramo da pediatri que trata patologias do coração de crianças','city_id'=>'16'],
['name'=>'cirurgia geral','description'=>'É a área que engloba todas as áreas cirúrgicas, sendo também subdividida','city_id'=>'6'],
['name'=>'cirurgia geral','description'=>'É a área que engloba todas as áreas cirúrgicas, sendo também subdividida','city_id'=>'16'],
['name'=>'cirurgia geral','description'=>'É a área que engloba todas as áreas cirúrgicas, sendo também subdividida','city_id'=>'977'],
['name'=>'cirurgia oncológica','description'=>'É o tratamento do câncer, ao lado da quimioterapia ou da radioterapia','city_id'=>'16'],
['name'=>'cirurgia plástica','description'=>'Correção das deformidades, malformações ou lesões que comprometem funções dos órgãos através de cirurgia de caráter reparador ou cirurgias estéticas','city_id'=>'16'],
['name'=>'cirurgia vascular','description'=>'É a especialidade médica que se ocupa do tratamento cirúrgicode doenças das artérias, veias e vasos linfáticos. Atua junto à Angiologia, especialidade responsável pelo estudo clínico dessas doenças. A angiologia encarrega-se do estudo, diagnóstico e tratamento clínico das doenças vasculares','city_id'=>'977'],
['name'=>'clínica geral','description'=>'É a área que engloba todas as áreas não cirúrgicas, sendo subdividida em várias outras especialidades','city_id'=>'3'],
['name'=>'clínica geral','description'=>'É a área que engloba todas as áreas não cirúrgicas, sendo subdividida em várias outras especialidades','city_id'=>'6'],
['name'=>'clínica geral','description'=>'É a área que engloba todas as áreas não cirúrgicas, sendo subdividida em várias outras especialidades','city_id'=>'16'],
['name'=>'clínica geral','description'=>'É a área que engloba todas as áreas não cirúrgicas, sendo subdividida em várias outras especialidades','city_id'=>'20'],
['name'=>'clínica geral','description'=>'É a área que engloba todas as áreas não cirúrgicas, sendo subdividida em várias outras especialidades','city_id'=>'977'],
['name'=>'clínicas','description'=>null,'city_id'=>'1'],
['name'=>'clínicas','description'=>null,'city_id'=>'3'],
['name'=>'clínicas','description'=>null,'city_id'=>'6'],
['name'=>'clínicas','description'=>null,'city_id'=>'13'],
['name'=>'clínicas','description'=>null,'city_id'=>'16'],
['name'=>'clínicas','description'=>null,'city_id'=>'19'],
['name'=>'clínicas','description'=>null,'city_id'=>'21'],
['name'=>'clínicas','description'=>null,'city_id'=>'178'],
['name'=>'clínicas','description'=>null,'city_id'=>'977'],
['name'=>'clínicas','description'=>null,'city_id'=>'4382'],
['name'=>'colonoscopia','description'=>'É um exame responsável por detectar o apaecimento de câncer no intestino','city_id'=>'16'],
['name'=>'coloproctologia','description'=>'É a parte da medicina que estuda e trata os problemas do intestino grosso (cólon), sigmoide e doenças do reto, canal anal e ânus','city_id'=>'16'],
['name'=>'coloproctologia','description'=>'É a parte da medicina que estuda e trata os problemas do intestino grosso (cólon), sigmoide e doenças do reto, canal anal e ânus','city_id'=>'977'],
['name'=>'densitometria óssea','description'=>'Avalia a coluna lombar, a região proximal do fêmur e o terço distal do rádio','city_id'=>'16'],
['name'=>'densitometria óssea','description'=>'Avalia a coluna lombar, a região proximal do fêmur e o terço distal do rádio','city_id'=>'178'],
['name'=>'densitometria óssea','description'=>'Avalia a coluna lombar, a região proximal do fêmur e o terço distal do rádio','city_id'=>'977'],
['name'=>'densitometria óssea','description'=>'Avalia a coluna lombar, a região proximal do fêmur e o terço distal do rádio','city_id'=>'4382'],
['name'=>'dermatologia','description'=>'Avalia a coluna lombar, a região proximal do fêmur e o terço distal do rádio','city_id'=>'16'],
['name'=>'dermatologia','description'=>'Avalia a coluna lombar, a região proximal do fêmur e o terço distal do rádio','city_id'=>'977'],
['name'=>'doppler de carótidas','description'=>'É um exame que utiliza o ultrassom para visualização dos vasos cervicais. (artérias responsáveis por levar o sengue ao cérebro e face)','city_id'=>'16'],
['name'=>'drogarias','description'=>'É um estabelecimento comercial que comercializa e dispensa medicamentos e insumos farmacêuticos contidos em suas embalagens originais provenientes da indústria. Diferente de uma farmácia, drogarias não podem manipular fórmulas oficinais e magistrais','city_id'=>'16'],
['name'=>'ecocardiograma','description'=>'É um exame que registra os impulsos elétricos do coração','city_id'=>'6'],
['name'=>'ecocardiograma','description'=>'É um exame que registra os impulsos elétricos do coração','city_id'=>'16'],
['name'=>'ecocardiograma','description'=>'É um exame que registra os impulsos elétricos do coração','city_id'=>'178'],
['name'=>'ecocardiograma pediátrico e fetal','description'=>'É um exame de ultrassom que permite avaliar se o coraçao do feto está se desenvolvendo adequadamente e se apresenta função normal dentro do últero','city_id'=>'16'],
['name'=>'eletrocardiograma','description'=>'É um exame de saúde na área de cardiologia no qual é feito o registro da variação dos potenciais elétricos gerados pela atividade elétrica do coração','city_id'=>'16'],
['name'=>'eletrocardiograma','description'=>'É um exame de saúde na área de cardiologia no qual é feito o registro da variação dos potenciais elétricos gerados pela atividade elétrica do coração','city_id'=>'178'],
['name'=>'eletroencefalograma','description'=>'É um método de monitoramento eletrofisiológico no qual é feito para registrar a atividade elétrica do cérebro','city_id'=>'16'],
['name'=>'eletroneuromiografia','description'=>'É um método de monitoramento eletrofisiológico no qual é feito para registrar a atividade elétrica do cérebro','city_id'=>'16'],
['name'=>'endocrinologia','description'=>'Especialidade que trata das glândulas e seus distúrbios','city_id'=>'6'],
['name'=>'endocrinologia','description'=>'Especialidade que trata das glândulas e seus distúrbios','city_id'=>'16'],
['name'=>'endocrinologia','description'=>'Especialidade que trata das glândulas e seus distúrbios','city_id'=>'977'],
['name'=>'endocrinologia e metabolismo','description'=>'é a área da Medicina responsável pelo cuidados aos hormônios, crescimento e glândulas como adrenal, tireoide, hipófise, pâncreas endócrino e outros','city_id'=>'16'],
['name'=>'endoscopia digestiva','description'=>'Esta especialidade médica ocupa-se do estudo dos mecanismo fisiopatológicos, diagnóstico e tratamento de enfermidades passíveis de abordagem por procedimentos endoscópicos e minimamente invasivos','city_id'=>'16'],
['name'=>'endoscopia nasal','description'=>'Exame utilizado para inspecionar a cavidade nasal','city_id'=>'16'],
['name'=>'farmácias de manipulação','description'=>'É o estabelecimento de saúde onde os medicamentos são preparados de acordo com a necessidade do cliente, de forma individualizada ou personalizada com base em receita emitida por profissional autorizado','city_id'=>'6'],
['name'=>'farmácias de manipulação','description'=>'É o estabelecimento de saúde onde os medicamentos são preparados de acordo com a necessidade do cliente, de forma individualizada ou personalizada com base em receita emitida por profissional autorizado','city_id'=>'16'],
['name'=>'fisioterapia','description'=>'É uma ciência da saúde aplicada ao estudo, diagnóstico, prevenção e tratamento de disfunções cinéticas funcionais de órgãos e sistemas. Sua gestão necessita do entendimento das estruturas e funções do corpo humano. Ela estuda, diagnostica, previne e trata os distúrbios, entre outros','city_id'=>'6'],
['name'=>'fisioterapia','description'=>'É uma ciência da saúde aplicada ao estudo, diagnóstico, prevenção e tratamento de disfunções cinéticas funcionais de órgãos e sistemas. Sua gestão necessita do entendimento das estruturas e funções do corpo humano. Ela estuda, diagnostica, previne e trata os distúrbios, entre outros','city_id'=>'8'],
['name'=>'fisioterapia','description'=>'É uma ciência da saúde aplicada ao estudo, diagnóstico, prevenção e tratamento de disfunções cinéticas funcionais de órgãos e sistemas. Sua gestão necessita do entendimento das estruturas e funções do corpo humano. Ela estuda, diagnostica, previne e trata os distúrbios, entre outros','city_id'=>'16'],
['name'=>'fisioterapia','description'=>'É uma ciência da saúde aplicada ao estudo, diagnóstico, prevenção e tratamento de disfunções cinéticas funcionais de órgãos e sistemas. Sua gestão necessita do entendimento das estruturas e funções do corpo humano. Ela estuda, diagnostica, previne e trata os distúrbios, entre outros','city_id'=>'19'],
['name'=>'fisioterapia','description'=>'É uma ciência da saúde aplicada ao estudo, diagnóstico, prevenção e tratamento de disfunções cinéticas funcionais de órgãos e sistemas. Sua gestão necessita do entendimento das estruturas e funções do corpo humano. Ela estuda, diagnostica, previne e trata os distúrbios, entre outros','city_id'=>'977'],
['name'=>'fonoaudiologia','description'=>'Especialidade médica que compreende o estudo da fonação e da audição, de seus distúrbios e das suas formas de tratamento','city_id'=>'6'],
['name'=>'fonoaudiologia','description'=>'Especialidade médica que compreende o estudo da fonação e da audição, de seus distúrbios e das suas formas de tratamento','city_id'=>'16'],
['name'=>'fonoaudiologia','description'=>'Especialidade médica que compreende o estudo da fonação e da audição, de seus distúrbios e das suas formas de tratamento','city_id'=>'977'],
['name'=>'gastroenterologia','description'=>'É o estudo, diagnóstico, tratamento e prevenção de doenças relacionadas ao aparelho digestivo, desde erros inatos do metabolismo, doença do trato gastrointestinal, doenças do fígado e cânceres','city_id'=>'3'],
['name'=>'gastroenterologia','description'=>'É o estudo, diagnóstico, tratamento e prevenção de doenças relacionadas ao aparelho digestivo, desde erros inatos do metabolismo, doença do trato gastrointestinal, doenças do fígado e cânceres','city_id'=>'6'],
['name'=>'gastroenterologia','description'=>'É o estudo, diagnóstico, tratamento e prevenção de doenças relacionadas ao aparelho digestivo, desde erros inatos do metabolismo, doença do trato gastrointestinal, doenças do fígado e cânceres','city_id'=>'16'],
['name'=>'gastroenterologia','description'=>'É o estudo, diagnóstico, tratamento e prevenção de doenças relacionadas ao aparelho digestivo, desde erros inatos do metabolismo, doença do trato gastrointestinal, doenças do fígado e cânceres','city_id'=>'977'],
['name'=>'geriatria','description'=>'É a subespecialidade médica que cuida dos idosos e articula seu tratamento com outras especialidades','city_id'=>'16'],
['name'=>'ginecologia e obstetrícia','description'=>'é a especialidade médica que aborda de forma integral a mulher. Trata desde as doenças infecciosas sexuais, gestação, alterações hormonais, reprodução','city_id'=>'3'],
['name'=>'ginecologia e obstetrícia','description'=>'é a especialidade médica que aborda de forma integral a mulher. Trata desde as doenças infecciosas sexuais, gestação, alterações hormonais, reprodução','city_id'=>'6'],
['name'=>'ginecologia e obstetrícia','description'=>'é a especialidade médica que aborda de forma integral a mulher. Trata desde as doenças infecciosas sexuais, gestação, alterações hormonais, reprodução','city_id'=>'16'],
['name'=>'ginecologia e obstetrícia','description'=>'é a especialidade médica que aborda de forma integral a mulher. Trata desde as doenças infecciosas sexuais, gestação, alterações hormonais, reprodução','city_id'=>'977'],
['name'=>'ginecologia e obstetrícia','description'=>'é a especialidade médica que aborda de forma integral a mulher. Trata desde as doenças infecciosas sexuais, gestação, alterações hormonais, reprodução','city_id'=>'4382'],
['name'=>'hematologia','description'=>'É o ramo da Medicina que estuda o sangue','city_id'=>'977'],
['name'=>'hepatologia','description'=>'É o estudo do fígado dos pontos de vista anatômico, fisiológico e patológico','city_id'=>'16'],
['name'=>'holter','description'=>'É um exame realizado por meio de um dispositivo portátil que pesa cerca de 100 gramas. O paciente deve ficar com ele acoplado na cintura por um período de 24 horas executando todas suas atividades rotineiras: andar, trabalhar, comer. O holter registra os batimentos cardíacos do indivíduo e detecta se houve alguma alteração ao longo do período','city_id'=>'16'],
['name'=>'holter','description'=>'É um exame realizado por meio de um dispositivo portátil que pesa cerca de 100 gramas. O paciente deve ficar com ele acoplado na cintura por um período de 24 horas executando todas suas atividades rotineiras: andar, trabalhar, comer. O holter registra os batimentos cardíacos do indivíduo e detecta se houve alguma alteração ao longo do período','city_id'=>'178'],
['name'=>'hospitais','description'=>'É um local destinado ao atendimento de doentes, para proporcionar o diagnóstico, que pode ser de vários tipos (laboratorial, clínico, cinesiológico-funcional) e o tratamento necessário','city_id'=>'16'],
['name'=>'hospitais','description'=>'É um local destinado ao atendimento de doentes, para proporcionar o diagnóstico, que pode ser de vários tipos (laboratorial, clínico, cinesiológico-funcional) e o tratamento necessário','city_id'=>'178'],
['name'=>'hospitais','description'=>'É um local destinado ao atendimento de doentes, para proporcionar o diagnóstico, que pode ser de vários tipos (laboratorial, clínico, cinesiológico-funcional) e o tratamento necessário','city_id'=>'977'],
['name'=>'hospitais','description'=>'É um local destinado ao atendimento de doentes, para proporcionar o diagnóstico, que pode ser de vários tipos (laboratorial, clínico, cinesiológico-funcional) e o tratamento necessário','city_id'=>'5270'],
['name'=>'hotéis','description'=>'É um estabelecimento comercial especializado em proporcionar acomodações para viajantes: a hospedagem mas por outras palavras, alojamentos pagos a curto prazo. Esse meio de hospedagem, geralmente, é classificado de uma a cinco estrelas, de acordo com o conforto, luxo e serviços oferecidos','city_id'=>'977'],
['name'=>'infectologia','description'=>'Prevenção, diagnóstico e tratamentos de infecções causadas por vírus, bactérias, fungos e parasitas (helmintologia, protozoologia, entomologia e artropodologia)','city_id'=>'16'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'3'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'6'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'13'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'16'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'17'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'19'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'20'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'21'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'22'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'178'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'977'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'4382'],
['name'=>'mamografia','description'=>'É um exame de diagnóstico por imagem, que tem como finalidade estudar o tecido mamário. Esse tipo de exame pode detectar um nódulo, mesmo que este ainda não seja palpável','city_id'=>'16'],
['name'=>'mamografia','description'=>'É um exame de diagnóstico por imagem, que tem como finalidade estudar o tecido mamário. Esse tipo de exame pode detectar um nódulo, mesmo que este ainda não seja palpável','city_id'=>'178'],
['name'=>'mamografia','description'=>'É um exame de diagnóstico por imagem, que tem como finalidade estudar o tecido mamário. Esse tipo de exame pode detectar um nódulo, mesmo que este ainda não seja palpável','city_id'=>'977'],
['name'=>'mamografia','description'=>'É um exame de diagnóstico por imagem, que tem como finalidade estudar o tecido mamário. Esse tipo de exame pode detectar um nódulo, mesmo que este ainda não seja palpável','city_id'=>'4382'],
['name'=>'mapa - monitorização ambul. da pressão arterial','description'=>'É o exame que mede a pressão arterial a cada 20 minutos, durante 24 horas, para a obtenção do registro da pressão arterial durante a vigília e o sono','city_id'=>'16'],
['name'=>'mapa - monitorização ambul. da pressão arterial','description'=>'É o exame que mede a pressão arterial a cada 20 minutos, durante 24 horas, para a obtenção do registro da pressão arterial durante a vigília e o sono','city_id'=>'178'],
['name'=>'massoterapia','description'=>'Tratamento terapêutico à base de massagens','city_id'=>'16'],
['name'=>'mastologia','description'=>'Estudo da conformação, do funcionamento e das afecções da mama','city_id'=>'16'],
['name'=>'mastologia','description'=>'Estudo da conformação, do funcionamento e das afecções da mama','city_id'=>'977'],
['name'=>'medicina de família e comunidade','description'=>'É uma especialidade médica caracterizada pela atenção integral à saúde e por levar em consideração a inserção do paciente na família e na comunidade','city_id'=>'1'],
['name'=>'medicina de família e comunidade','description'=>'É uma especialidade médica caracterizada pela atenção integral à saúde e por levar em consideração a inserção do paciente na família e na comunidade','city_id'=>'13'],
['name'=>'medicina estética','description'=>'Ajuda a rejuvenescer sem cirurgias','city_id'=>'16'],
['name'=>'nefrologia','description'=>'É a parte da medicina que estuda e trata clinicamente as doenças do rim, como insuficiência renal','city_id'=>'16'],
['name'=>'nefrologia','description'=>'É a parte da medicina que estuda e trata clinicamente as doenças do rim, como insuficiência renal','city_id'=>'977'],
['name'=>'neurologia','description'=>'É a parte da medicina que estuda e trata o sistema nervoso','city_id'=>'16'],
['name'=>'neurologia','description'=>'É a parte da medicina que estuda e trata o sistema nervoso','city_id'=>'977'],
['name'=>'neuropsicologia','description'=>'É um procedimento da psicologia que estuda relações entre o cérebro e as manifestações do comportamento humano','city_id'=>'16'],
['name'=>'nutrição','description'=>'Planeja, administr e coordena programas de alimentação e nutrição','city_id'=>'6'],
['name'=>'nutrição','description'=>'Planeja, administr e coordena programas de alimentação e nutrição','city_id'=>'16'],
['name'=>'nutrição','description'=>'Planeja, administr e coordena programas de alimentação e nutrição','city_id'=>'977'],
['name'=>'nutrição esportiva','description'=>'É a área que aplica a base de conhecimentos em: nutrição, fisiologia e bioquímica no esporte e atividade física. Os principais objetivos da nutrição esportiva são: Aumentar o desempenho físico, desportivo, evolucional e hibernolar do atleta','city_id'=>'16'],
['name'=>'nutrologia','description'=>'Diagnóstico, prevenção e tratamento de doenças do comportamento alimentar','city_id'=>'16'],
['name'=>'odontologia','description'=>'Odont especialidade paramédica que se dedica ao estudo e tratamento dos dentes e de suas afecções; dentistaria','city_id'=>'16'],
['name'=>'oftalmologia','description'=>'É a parte da medicina que estuda e trata os distúrbios dos olhos','city_id'=>'6'],
['name'=>'oftalmologia','description'=>'É a parte da medicina que estuda e trata os distúrbios dos olhos','city_id'=>'16'],
['name'=>'oftalmologia','description'=>'É a parte da medicina que estuda e trata os distúrbios dos olhos','city_id'=>'977'],
['name'=>'oncologia','description'=>'É a especialidade médica que estuda os cancros (tumores malignos) e a forma de como essas doenças se desenvolvem no organismo, procurando seu tratamento','city_id'=>'977'],
['name'=>'ortopedia e traumatologia','description'=>'E a parte da medicina que estuda e trata as doenças do sistema osteomuscular, locomoção, crescimento, deformidades e as fraturas','city_id'=>'6'],
['name'=>'ortopedia e traumatologia','description'=>'E a parte da medicina que estuda e trata as doenças do sistema osteomuscular, locomoção, crescimento, deformidades e as fraturas','city_id'=>'16'],
['name'=>'ortopedia e traumatologia','description'=>'E a parte da medicina que estuda e trata as doenças do sistema osteomuscular, locomoção, crescimento, deformidades e as fraturas','city_id'=>'977'],
['name'=>'óticas','description'=>'Lugar onde é possível vender ou fabricar óculos','city_id'=>'178'],
['name'=>'otorrinolaringologia','description'=>'É a parte da medicina que estuda e trata as doenças da orelha, nariz, seios paranasais, faringe e laringe','city_id'=>'16'],
['name'=>'otorrinolaringologia','description'=>'É a parte da medicina que estuda e trata as doenças da orelha, nariz, seios paranasais, faringe e laringe','city_id'=>'977'],
['name'=>'pediatria','description'=>'É a parte da medicina que estuda e trata crianças e adolecentes','city_id'=>'6'],
['name'=>'pediatria','description'=>'É a parte da medicina que estuda e trata crianças e adolecentes','city_id'=>'16'],
['name'=>'pediatria','description'=>'É a parte da medicina que estuda e trata crianças e adolecentes','city_id'=>'977'],
['name'=>'pediatria','description'=>'É a parte da medicina que estuda e trata crianças e adolecentes','city_id'=>'4382'],
['name'=>'pneumologia','description'=>'É a parte da medicina que estuda e trata o sistema respiratório e pulmonar','city_id'=>'16'],
['name'=>'psicanálise','description'=>'Método terapêutico criado por S. Freud, empregado em casos de neurose e psicose, que consiste fundamentalmente na interpretação, por um psicanalista, dos conteúdos inconscientes de palavras, ações e produções imaginárias de um indivíduo, com base nas associações livres e na transferência','city_id'=>'16'],
['name'=>'psicologia','description'=>'Psic ciência que trata dos estados e processos mentais, do comportamento do ser humano e de suas interações com um ambiente físico e social','city_id'=>'6'],
['name'=>'psicologia','description'=>'Psic ciência que trata dos estados e processos mentais, do comportamento do ser humano e de suas interações com um ambiente físico e social','city_id'=>'16'],
['name'=>'psicologia','description'=>'Psic ciência que trata dos estados e processos mentais, do comportamento do ser humano e de suas interações com um ambiente físico e social','city_id'=>'977'],
['name'=>'psiquiatria','description'=>'é a parte da medicina que previne e trata ao transtornos mentais e comportamentais','city_id'=>'6'],
['name'=>'psiquiatria','description'=>'é a parte da medicina que previne e trata ao transtornos mentais e comportamentais','city_id'=>'16'],
['name'=>'raios-x','description'=>'São ondas eletromagnéticas que possuem a capacidade de atravessar corpos de baixa densidade e são absorvidos por materiais de densidade maior. O raio X é um tipo de radiação eletromagnética com frequências superiores à radiação ultravioleta, ou seja, maiores que 1018 Hz','city_id'=>'16'],
['name'=>'raios-x','description'=>'São ondas eletromagnéticas que possuem a capacidade de atravessar corpos de baixa densidade e são absorvidos por materiais de densidade maior. O raio X é um tipo de radiação eletromagnética com frequências superiores à radiação ultravioleta, ou seja, maiores que 1018 Hz','city_id'=>'178'],
['name'=>'raios-x','description'=>'São ondas eletromagnéticas que possuem a capacidade de atravessar corpos de baixa densidade e são absorvidos por materiais de densidade maior. O raio X é um tipo de radiação eletromagnética com frequências superiores à radiação ultravioleta, ou seja, maiores que 1018 Hz','city_id'=>'977'],
['name'=>'ressonância magnética','description'=>'É um método de diagnóstico por imagem que usa ondas de radiofrequência e um forte campo magnético para obter informações detalhadas dos órgãos e tecidos internos do corpo, sem a utilização de radiação ionizante','city_id'=>'16'],
['name'=>'ressonância magnética','description'=>'É um método de diagnóstico por imagem que usa ondas de radiofrequência e um forte campo magnético para obter informações detalhadas dos órgãos e tecidos internos do corpo, sem a utilização de radiação ionizante','city_id'=>'178'],
['name'=>'reumatologia','description'=>'É a especialidade médica que trata das doenças do tecido conjuntivo, articulações e doenças autoimunes. Diferente do senso comum o reumatologista não trata somente reumatismo','city_id'=>'16'],
['name'=>'reumatologia','description'=>'É a especialidade médica que trata das doenças do tecido conjuntivo, articulações e doenças autoimunes. Diferente do senso comum o reumatologista não trata somente reumatismo','city_id'=>'977'],
['name'=>'terapia ocupacional','description'=>'Estuda e emprega atividades de trabalho e lazer no tratamento de distúrbios físicos ou mentais e de desajustes emocionais e sociais. O profissional utiliza tecnologias e atividades diversas para promover a autonomia de indivíduos com dificuldade de integrar-se à vida social em razão de problemas físicos, mentais ou emocionais. Ele elabora planos de reabilitação e adaptação, buscando desenvolver no paciente autoconfiança','city_id'=>'16'],
['name'=>'teste da orelhinha','description'=>'É um teste obrigatório por lei que deve ser feito ainda na maternidade, nos bebês para avaliar a audição e detectar precocemente algum grau de surdez no bebê','city_id'=>'16'],
['name'=>'teste do pezinho','description'=>'É um exame feito a partir de sangue coletado do calcanhar do bebê. Ele permite identificar doenças como hipotireoidismo congênito, fenilcetonúria e hemoglobinopatias (doenças que afetam o sangue)','city_id'=>'16'],
['name'=>'teste ergométrico','description'=>'Serve para a avaliação ampla do funcionamento cardiovascular, quando submetido a esforço físico gradualmente crescente, em esteira rolante. São observados os sintomas, os comportamentos da frequência cardíaca, da pressão arterial e do eletrocardiograma antes, durante e após o esforço','city_id'=>'16'],
['name'=>'teste ergométrico','description'=>'Serve para a avaliação ampla do funcionamento cardiovascular, quando submetido a esforço físico gradualmente crescente, em esteira rolante. São observados os sintomas, os comportamentos da frequência cardíaca, da pressão arterial e do eletrocardiograma antes, durante e após o esforço','city_id'=>'178'],
['name'=>'tomografia computadorizada','description'=>'E o exame que fornece imagens mais precisas do que as do Raio X, detectando alterações muito pequenas em ossos, tecidos, órgãos e outras estruturas do corpo. É atualmente o exame de escolha para investigar nódulos ou tumores, e também vasos pulmonares e cerebrais','city_id'=>'16'],
['name'=>'tomografia computadorizada','description'=>'E o exame que fornece imagens mais precisas do que as do Raio X, detectando alterações muito pequenas em ossos, tecidos, órgãos e outras estruturas do corpo. É atualmente o exame de escolha para investigar nódulos ou tumores, e também vasos pulmonares e cerebrais','city_id'=>'178'],
['name'=>'tomografia computadorizada','description'=>'E o exame que fornece imagens mais precisas do que as do Raio X, detectando alterações muito pequenas em ossos, tecidos, órgãos e outras estruturas do corpo. É atualmente o exame de escolha para investigar nódulos ou tumores, e também vasos pulmonares e cerebrais','city_id'=>'977'],
['name'=>'ultrassonografia','description'=>'É um método diagnóstico muito recorrente na medicina que utiliza o eco gerado através de ondas ultrassônicas de alta frequência para visualizar, em tempo real, as estruturas internas do organismo','city_id'=>'16'],
['name'=>'ultrassonografia','description'=>'É um método diagnóstico muito recorrente na medicina que utiliza o eco gerado através de ondas ultrassônicas de alta frequência para visualizar, em tempo real, as estruturas internas do organismo','city_id'=>'178'],
['name'=>'ultrassonografia','description'=>'É um método diagnóstico muito recorrente na medicina que utiliza o eco gerado através de ondas ultrassônicas de alta frequência para visualizar, em tempo real, as estruturas internas do organismo','city_id'=>'977'],
['name'=>'ultrassonografia','description'=>'É um método diagnóstico muito recorrente na medicina que utiliza o eco gerado através de ondas ultrassônicas de alta frequência para visualizar, em tempo real, as estruturas internas do organismo','city_id'=>'4382'],
['name'=>'ultrassonografia morfológica','description'=>'É um exame de rotina feito normalmente entre 20 e 24 semanas de gravidez. Serve para avaliar o desenvolvimento do bebê com bastante detalhe, incluindo os órgãos internos. Nessaultrassonografia também já dá para descobrir o sexo do bebê, desde que ele "colabore"','city_id'=>'16'],
['name'=>'urologia','description'=>'É a parte da medicina que estuda e trata cirurgicamente e clinicamente os problemas do sistema urinário e do sistema reprodutor masculino e feminino','city_id'=>'16'],
['name'=>'urologia','description'=>'É a parte da medicina que estuda e trata cirurgicamente e clinicamente os problemas do sistema urinário e do sistema reprodutor masculino e feminino','city_id'=>'977'],
['name'=>'videolaringoscopia','description'=>'É um exame realizado no consultório por um otorrinolaringologista, com o objetivo de visualizar regiões da cavidade oral, orofaringe, hipofaringe e laringe. Procuram-se lesões ou sinais sugestivos de doenças que acometam a boca, garganta, base da língua, pregas vocais entre outros','city_id'=>'16'],
['name'=>'clínicas','description'=>null,'city_id'=>'804'],
['name'=>'laboratórios','description'=>'É uma sala ou espaço físico devidamente equipado com instrumentos de medida próprios para a realização de experimentos e pesquisas científicas[1] [2] diversas, dependendo do ramo da ciência para o qual foi planejado','city_id'=>'804'],
                                                
        ]);

        $this->command->info('Especialidade médicas importadas com sucesso!');
    }
}